name: unity build plugins

on: 
  workflow_dispatch:
  push:
    paths: 
      - unity/native_src/**
      - unity/native_src_il2cpp/**
      - unity/cli/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/unity_build_plugins.yml

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: BuildAndroid
        uses: ./.github/workflows/composites/unity-build-plugins/android/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4

  ios:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4
      - name: BuildiOS
        uses: ./.github/workflows/composites/unity-build-plugins/ios/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4

  osx:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4
      - name: BuildOSX
        uses: ./.github/workflows/composites/unity-build-plugins/osx/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4

  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: BuildWindows
        uses: ./.github/workflows/composites/unity-build-plugins/windows/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4

  linux64:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: BuildLinux
        uses: ./.github/workflows/composites/unity-build-plugins/linux/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4
